### ISSUE TITLE
Write terraform code

### ISSUE THREAD

**Issue by olliejth** [olliejth/Week-13-LMNH-Plant-Health#24]

**Comment by YakMan101** [comment]
As a developer I want to fill out my terraform files with code so that I can provision all my cloud resources with a single command.

- [ ] Short term ETL pipeline
    - Eventbridge Schedule (1 min)
    - Lmabda to run short-term-etl container
    -  Cloudwatch for logs
- [ ] Long term ETL pipeline
    - Eventbridge Schedule (24 hrs)
    - ECS task to run long-term-etl container
    - Cloudwatch for logs
- [ ] EC2 to host dashboard
